In [1]:
%run Blackjack.py

In [2]:
S = 10*10*2
pi = np.zeros(S, dtype=np.int32)

for s in range(S):
    game = np.asarray(np.unravel_index(s, (10, 10, 2))) + [12, 1, 0]
    if game[0] < 17:
        pi[s] = 0
    else:
        pi[s] = 1

In [8]:

bj = Blackjack(0, 0, pi)
bj.play()
print(bj.get_states())
print(bj.get_actions())
print(bj.get_rewards())

Hand: (12, 0)	Dealer: 1
Hand: (15, 0)	Dealer: 1
Hand: (21, 0)	Dealer: 1
Hand: (21, 0)	Dealer: 21
[  0  60 180  -1]
[0. 0. 0.]
[0. 0. 0.]
